### ISSUE TITLE
Crash in test12.py

### ISSUE THREAD

**Issue by jwreep** [Goobley/LightweaverSamples#1]
The last line of Test12.py crashes with current version of LW.  Have any updates changed the syntax?

`
ctxCons, IwaveCons, _ = synth_8542(atmosCons, conserve=True, useNe=False, stokes=False)
`

Traceback (most recent call last):
  File "Test12.py", line 118, in <module>
    ctxCons, IwaveCons, _ = synth_8542(atmosCons, conserve=True, useNe=False, stokes=False)
  File "Test12.py", line 58, in synth_8542
    iterate_ctx(ctx, atmos, eqPops, prd=False, updateLte=False)
  File "Test12.py", line 26, in iterate_ctx
    delta = ctx.stat_equil()
  File "Source/CAtmosphere.pyx", line 2005, in lightweaver.LwCompiled.LwContext.stat_equil
  File "Source/CAtmosphere.pyx", line 2034, in lightweaver.LwCompiled.LwContext.stat_equil
AttributeError: 'lightweaver.LwCompiled.LwContext' object has no attribute 'nr_post_update'

**Comment by Goobley** [comment]
Sorry about that. I've been working on the Newton-Raphson scheme for when the electron density isn't known a priori. I've been doing this though monkey-patching. So currently `LwCompiled.LwContext` and `lw.Context` are not the same object -- this will be fixed soon, as the experimentation on this front is pretty much done. However, as the `lw.` scheme is better than a load of imports, it makes sense to move to this anyway. Just pushed the fixes that were sitting on my local machine from testing, and the file has been renamed `SimpleLineTest.py` from `Test12.py` (tests 1-11 being for incomplete versions of Lightweaver that no longer exist!) 

Fixed in 73b4c06.
